### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by bil-elmoussaoui** [flathub/com.github.paolostivanin.OTPClient#1]
I just saw your app on flathub and tried to use it 
Here's what i get when i try to run it 
```
Cannot allocate memory
```

**Comment by paolostivanin** [comment]
Hello,
what distro are you using? Some distros (like Ubuntu 16.04) use by default a very low memlock limit and, therefore, it must be increased before using this app.

https://github.com/paolostivanin/OTPClient#known-issues

**Comment by paolostivanin** [comment]
I have just added a better error message on master. Will prepare a release soon

https://github.com/paolostivanin/OTPClient/commit/fc1b20e2805f02af1ad80ef332875ac0776ba1ed

**Comment by TingPing** [comment]
It fails on Fedora also.

**Comment by bil-elmoussaoui** [comment]
I'm using arch

**Comment by bil-elmoussaoui** [comment]
And when i run `ulimit -l` i get `1024`

**Comment by paolostivanin** [comment]
@bil-elmoussaoui that's interesting because Arch is also my "daily driver" linux distro. And my default value is `unlimited`, I didn't change it.

@TingPing I tried Fedora 26 and 27 on virtualbox and everything was working fine some days ago. I'll check again

**Comment by paolostivanin** [comment]
working on a fix. See [issue 31](https://github.com/paolostivanin/OTPClient/issues/31)

**Comment by paolostivanin** [comment]
fixed with v1.0.3
