### ISSUE TITLE
Bad UX for deleting keys

### ISSUE THREAD

**Issue by Yajo** [flathub/com.github.paolostivanin.OTPClient#23]
Hi! Thanks for this wonderful app! 😃 

I just deleted some keys for the 1st time and found out that the workflow for deleting keys feels like driving without brakes:

1. Hit "-"
2. Accept dialog with long text.
3. Click on row to delete.

If you click on the wrong row for accident, you're doomed.

Example: you follow those steps to delete one item. You don't realize the "-" button is red, and then click on another row because you need that OTP code. 💣 💥 🤯 

My proposal:

1. Click row.
2. Click "-".
3. Dialog: "Are you sure you want to delete this item? You won't be able to recover it unless you have another backup!" Buttons: "Delete" (red) and "Cancel"

Simpler and more clear. It'll take more time to delete many items, but at the same time it will feel safe.

**Comment by paolostivanin** [comment]
hello! thanks for reporting this!
Could you please open it at https://github.com/paolostivanin/OTPClient/issues ?

thanks :)
