### ISSUE TITLE
Doesn't remember last used database

### ISSUE THREAD

**Issue by Lancer11211** [flathub/com.github.paolostivanin.OTPClient#35]
I've installed the latest version from flathub but every time I reopen otpclient, it opens the default empty database and I've to go for the "Change database" menu item and select my db again and again. The native version(2.4.6 on ubuntu) doesn't have this issue.

**Comment by paolostivanin** [comment]
can u pls open it here https://github.com/paolostivanin/OTPClient/issues ? thx
