### ISSUE TITLE
Remove `unshare=network` from manifest

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.github.paolostivanin.OTPClient#46]
https://github.com/flathub/com.github.paolostivanin.OTPClient/blob/579f968411b1524882c58032a28a674d57263b4c/com.github.paolostivanin.OTPClient.yaml#L12

The default is no network access unless you use `--share=network`. The various `nosocket, nodevice, unshare` etc. are meant to be used with `flatpak run` to override values set in manifest, not in the manifest itself.

**Comment by paolostivanin** [comment]
done thanks
