### ISSUE TITLE
Impossible to show the "file chooser dialog" popup UI - it doesn't appears

### ISSUE THREAD

**Issue by codingepaduli** [flathub/com.github.paolostivanin.OTPClient#51]
Impossible to import plain or encrypted file - The  "file chooser dialog" popup UI doesn't appears 
Impossible to export plain or encrypted file - The  "file chooser dialog" popup UI doesn't appears 
Impossible to scan a QR Code from file - The  "file chooser dialog" popup UI doesn't appears 

Others dialogs like "insert a new row" or "settings" appears correctly.

Distro:	Debian GNU/Linux 12 (bookworm)
flatpak --version: Flatpak 1.14.4
Memory:
```
               total        used        free      shared  buff/cache   available
Mem:           7,1Gi       2,5Gi       2,4Gi        38Mi       2,6Gi       4,6Gi
Swap:          9,3Gi       432Mi       8,9Gi
```

Installed app: ``com.github.paolostivanin.OTPClient   3.6.0  runtime  org.gnome.Platform/x86_64/45``

I **fixed** the following warning with the command ``flatpak override --user --filesystem=xdg-run/gvfsd com.github.paolostivanin.OTPClient``

```
(otpclient:2): GVFS-WARNING **: 12:35:08.823: The peer-to-peer connection failed: Errore nel recuperare informazioni per il file «/run/user/1001/gvfsd»: File o directory non esistente. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
```

Now, when I run the app with the command ``flatpak run com.github.paolostivanin.OTPClient``, no log messages are shown.

I also tried to install the Debug options, but running the app with the command ``flatpak run --devel com.github.paolostivanin.OTPClient``, no log messages are shown.

**Comment by paolostivanin** [comment]
Interesting, thanks for reporting this. May I ask where is the file stored? On the same disk or some other place?

May be related to https://github.com/flathub/flathub/issues/2180
